/*
  Find the Difference


Given two strings s and t which consist of only lowercase letters.

String t is generated by random shuffling string s and then add one more letter
at a random position.

Find the letter that was added in t.

Example:

Input:
s = "abcd"
t = "abcde"

Output:
e

Explanation:
'e' is the letter that was added.
*/

// Simple hashMap solution, beats 96.78 % of cpp submissions.

class Solution {
   public:
    char findTheDifference(string s, string t) {
        ios_base::sync_with_stdio(false);
        cin.tie(NULL);

        unordered_map<char, int> hashMap;
        int sLen = s.length();
        int tLen = t.length();

        for (int idx = 0; idx < tLen; idx++) {
            hashMap[t[idx]] += 1;
            if (idx < sLen) hashMap[s[idx]] -= 1;
        }

        for (auto& map : hashMap) {
            if (map.second == 1) return map.first;
        }

        return 'z';
    }
};